kind: Template
apiVersion: v1
metadata:
  name: clowder-plugin
objects:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: clowder-plugin
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: clowder-plugin
    namespace: clowder-plugin
    labels:
      app: clowder-plugin
      app.kubernetes.io/component: clowder-plugin
      app.kubernetes.io/instance: clowder-plugin
      app.kubernetes.io/part-of: clowder-plugin
      app.openshift.io/runtime-namespace: clowder-plugin
    annotations:
      kube-linter.io/ignore-all: "no checks needed"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: clowder-plugin
    template:
      metadata:
        labels:
          app: clowder-plugin
      spec:
        containers:
          - name: clowder-plugin
            image: ${IMAGE}:${IMAGE_TAG}
            ports:
              - containerPort: 9001
                protocol: TCP
            imagePullPolicy: Always
            volumeMounts:
              - name: console-serving-cert
                readOnly: true
                mountPath: /var/serving-cert
        volumes:
          - name: console-serving-cert
            secret:
              secretName: console-serving-cert
              defaultMode: 420
        restartPolicy: Always
        dnsPolicy: ClusterFirst
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
    name: clowder-plugin
    namespace: clowder-plugin
    labels:
      app: clowder-plugin
      app.kubernetes.io/component: clowder-plugin
      app.kubernetes.io/instance: clowder-plugin
      app.kubernetes.io/part-of: clowder-plugin
  spec:
    ports:
      - name: 9001-tcp
        protocol: TCP
        port: 9001
        targetPort: 9001
    selector:
      app: clowder-plugin
    type: ClusterIP
    sessionAffinity: None
- apiVersion: console.openshift.io/v1alpha1
  kind: ConsolePlugin
  metadata:
    name: clowder-plugin
  spec:
    displayName: 'OpenShift Console Demo Plugin'
    service:
      name: clowder-plugin
      namespace: clowder-system
      port: 9001
      basePath: '/'
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: clowder-plugin-allow-from-console-namespace
  spec:
    podSelector: {}
    ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-console
parameters:
- name: IMAGE_TAG
  value: latest
- name: IMAGE
  value: quay.io/redhat-services-prod/hcm-eng-prod-tenant/clowder-plugin